# Generated by Django 4.2 on 2023-06-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='condition',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='test_file',
            field=models.JSONField(),
        ),
    ]
