# Generated by Django 4.2 on 2023-06-11 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0002_alter_task_condition_alter_task_test_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='test_file',
            new_name='test_data',
        ),
    ]
