# Generated by Django 4.2 on 2023-06-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0003_rename_test_file_task_test_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='source_file',
            field=models.TextField(),
        ),
    ]
